# Generated by Django 6.0.5 on 2026-05-24 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='trips.spot'),
        ),
    ]
