# Generated by Django 6.0.5 on 2026-05-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_expense_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='currency',
            field=models.CharField(blank=True, choices=[('JPY', '円'), ('KRW', 'ウォン'), ('USD', 'ドル')], default='', max_length=3),
        ),
    ]
