# Generated by Django 6.0.5 on 2026-05-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_spot_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
