# Generated by Django 6.0.5 on 2026-05-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_soft_delete_and_user_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='visibility',
            field=models.CharField(choices=[('public', '公開'), ('private', '非公開（PIN保護）')], default='public', max_length=10),
        ),
    ]
